class Admin::LeavesController < AdminController
  before_action :set_leave, only: [:show, :edit, :update, :destroy, :recommend, :change]

  # GET /leaves
  # GET /leaves.json
  def index
    @url = request.url
    params[:employee] ||= Employee.all.ids
    @employees = Employee.find(params[:employee])
    if params[:recommended].to_i == 1
      @status = "recommended"
      @leaves = Leave.where(employee: @employees, recommended: true)
    elsif params[:approved].to_i == 1
      @status = "approved"
      @leaves = Leave.where(employee: @employees, approved: true)
    else
      @status = ""
      @leaves = Leave.where(employee: @employees)
    end
    respond_to do |format| 
      format.html 
      format.pdf do
        info = {
           :Title => @leaves.count.to_s+" #{@status.capitalize} leave(s) - RwarriMS Admin",
           :Author => current_employee.names,
           :Subject => "Leaves - RwarriMS Admin",
           :Keywords => "ruby pdf leaves rwarrims",
           :Creator => "RwarriMS Admin",
           :Producer => "Prawn",
           :CreationDate => Time.now
          }
          pdf = Prawn::Document.new(info: info) do |pdf|
            pdf.image Rails.root.join("app/assets/images","rwarri-banner.png"), width: 600, position: -40
            pdf.font_size 20
            pdf.move_down 20
            pdf.text @leaves.count.to_s+" #{@status.capitalize} leave(s) - RwarriMS Admin", style: :bold
            pdf.move_down 10
            pdf.font_size 12
            pdf.stroke_color "000000"
            @leaves.each do |leave|
              pdf.stroke do
                pdf.horizontal_rule
              end
              pdf.move_down 10
              pdf.text "<b>Reason #{leave.reason}", :inline_format => true
              pdf.text "<b>Category</b> #{helpers.getCategoryId leave.category}", :inline_format => true
              pdf.text "<b>By</b> #{leave.employee.names}", :inline_format => true
              pdf.text "<b>Start</b> #{leave.start.strftime("%r on %a %d %b %Y")} (#{helpers.time_ago_in_words(leave.start)} #{leave.start > DateTime.now ? "from now" : "ago"})", :inline_format => true
              pdf.text "<b>End</b> #{leave.end.strftime("%r on %a %d %b %Y")} (#{helpers.time_ago_in_words(leave.end)} #{leave.end > DateTime.now ? "from now" : "ago"})", :inline_format => true
              pdf.text "<b>Expected to be at workplace</b> #{leave.expected.strftime("%r on %a %d %b %Y")} (#{helpers.time_ago_in_words(leave.expected)} #{leave.expected > DateTime.now ? "from now" : "ago"})", :inline_format => true
              @e=Employee.find(leave.recommended_by) if leave.recommended
              pdf.text "<b>Recommended</b> #{leave.recommended} #{"by "+@e.names if leave.recommended}", :inline_format => true
              if leave.recommended
                @e=Employee.find(leave.approved_by) if leave.approved
                pdf.text "<b>Approved</b> #{leave.approved} #{"by "+@e.names if leave.approved}", :inline_format => true
              end
            end
            pdf.move_down 10
            pdf.stroke do
              pdf.horizontal_rule
            end
            pdf.move_down 10
            pdf.font_size 12
            pdf.text "Generated <b>at #{DateTime.now.strftime("%r on %a %d %b %Y")}</b>", :inline_format => true
            pdf.text "Generated by <b>Uwizeye Belange</b>", :inline_format => true
            pdf.text "Generated by <color rgb='#0000ff'><u><link href='https://rwarrims-beta.herokuapp.com'>RwarriMS</link></u></color> - Rwarri Management System", :inline_format => true
            pdf.text "Content © Copyright <color rgb='#0000ff'><u><link href='https://rwarri.com'>RWARRI</link></u></color> - Rwanda Rural Rehabilitation Initiative", :inline_format => true

          end
          send_data pdf.render, type: "application/pdf", disposition: "inline"
      end
    end
  end

  def show
    @url = request.url
    respond_to do |format| 
      format.html 
      format.pdf do
        info = {
           :Title => "Leave - RwarriMS Admin",
           :Author => current_employee.names,
           :Subject => "Leave - RwarriMS Admin",
           :Keywords => "ruby pdf leaves rwarrims",
           :Creator => "RwarriMS Admin",
           :Producer => "Prawn",
           :CreationDate => Time.now
          }
          pdf = Prawn::Document.new(info: info) do |pdf|
            pdf.image Rails.root.join("app/assets/images","rwarri-banner.png"), width: 600, position: -40
            pdf.font_size 20
            pdf.move_down 20
            pdf.text "Leave - RwarriMS Admin", style: :bold
            pdf.move_down 10
            pdf.font_size 12
            pdf.stroke_color "000000"
            leave = @leave
              pdf.stroke do
                pdf.horizontal_rule
              end
              pdf.move_down 10
              pdf.text "<b>Reason #{leave.reason}", :inline_format => true
              pdf.text "<b>Category</b> #{helpers.getCategoryId leave.category}", :inline_format => true
              pdf.text "<b>By</b> #{leave.employee.names}", :inline_format => true
              pdf.text "<b>Start</b> #{leave.start.strftime("%r on %a %d %b %Y")} (#{helpers.time_ago_in_words(leave.start)} #{leave.start > DateTime.now ? "from now" : "ago"})", :inline_format => true
              pdf.text "<b>End</b> #{leave.end.strftime("%r on %a %d %b %Y")} (#{helpers.time_ago_in_words(leave.end)} #{leave.end > DateTime.now ? "from now" : "ago"})", :inline_format => true
              pdf.text "<b>Expected to be at workplace</b> #{leave.expected.strftime("%r on %a %d %b %Y")} (#{helpers.time_ago_in_words(leave.expected)} #{leave.expected > DateTime.now ? "from now" : "ago"})", :inline_format => true
              @e=Employee.find(leave.recommended_by) if leave.recommended
              pdf.text "<b>Recommended</b> #{leave.recommended} #{"by "+@e.names if leave.recommended}", :inline_format => true
              if leave.recommended
                @e=Employee.find(leave.approved_by) if leave.approved
                pdf.text "<b>Approved</b> #{leave.approved} #{"by "+@e.names if leave.approved}", :inline_format => true
              end
            pdf.move_down 10
            pdf.stroke do
              pdf.horizontal_rule
            end
            pdf.move_down 10
            pdf.font_size 12
            pdf.text "Generated <b>at #{DateTime.now.strftime("%r on %a %d %b %Y")}</b>", :inline_format => true
            pdf.text "Generated by <b>Uwizeye Belange</b>", :inline_format => true
            pdf.text "Generated by <color rgb='#0000ff'><u><link href='https://rwarrims-beta.herokuapp.com'>RwarriMS</link></u></color> - Rwarri Management System", :inline_format => true
            pdf.text "Content © Copyright <color rgb='#0000ff'><u><link href='https://rwarri.com'>RWARRI</link></u></color> - Rwanda Rural Rehabilitation Initiative", :inline_format => true

          end
          send_data pdf.render, type: "application/pdf", disposition: "inline"
      end
    end
  end

  def recommend
    @p = helpers.current_employee.position
  end

  def destroy
  end

  def edit
  end

  def change
    respond_to do |format|
      @leave.recommended = change_params[:recommended]
      @leave.approved = change_params[:approved]
      if change_params[:recommended] == "1"
        @leave.recommended_by = helpers.current_employee.id
        @leave.date_recommended = DateTime.now
      end
      if change_params[:approved] == "1"
        if helpers.current_employee.position.to_i != 6
          @leave.errors.add(:base,"Only Executive Director can approve leaves")
        else
          @leave.approved_by = helpers.current_employee.id
          @leave.date_approved = DateTime.now
        end
      end
      if @leave.save
        format.html { redirect_to admin_leave_path(@leave), notice: 'Leave was successfully updated.' }
        format.json { render :show, status: :ok, location: @leave }
      else
        format.html { render :edit }
        format.json { render json: @leave.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @leave.update(leave_params)
        format.html { redirect_to admin_leave_path(@leave), notice: 'Leave was successfully updated.' }
        format.json { render :show, status: :ok, location: @leave }
      else
        format.html { render :edit }
        format.json { render json: @leave.errors, status: :unprocessable_entity }
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_leave
      @leave = Leave.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def leave_params
      params.require(:leave).permit(:reason, :start, :end, :expected, :category)
    end

    def change_params
      params.require(:leave).permit(:recommended, :approved)
    end
end
